######################################################################
#
#  Just a wrapper to launch the 'big' Makefile from above...
#  For details read ../Makefile.
#
######################################################################
# $Log: Makefile,v $
# Revision 1.5  2002/03/20 21:26:29  fbarriere
# Now just a wrapper around the unique Makefile you should find
# in the parent directory.
#
# Revision 1.4  2002/03/12 20:41:45  nikai
# sgml2html language support
#
# Revision 1.3  2001/09/01 00:20:09  mones
# Deleted my stupid revision comment. I shouldn't play with cvs late night...
#
# Revision 1.2  2001/09/01 00:11:12  mones
# added Spanish to list of generated languages
#
# Revision 1.1  2001/08/29 21:31:27  fbarriere
# Created.
#
######################################################################

.DEFAULT:
	$(MAKE) -C .. ALL_TYPES=manual $@
